export const surpriseMePrompts = [
    "A mystical forest with glowing mushrooms and fireflies.",
    "An otherworldly city floating in the clouds.",
    "A futuristic cityscape with holographic advertisements.",
    "An alien planet with multiple moons.",
    "A serene beach at sunset with palm trees.",
    "A creepy abandoned mansion with overgrown vines.",
    "A post-apocalyptic wasteland with ruins and desolation.",
    "A lush green valley with a river flowing through it.",
    "A snowy mountain range with a frozen lake.",
    "A bustling street market in a foreign country.",
    "A magical underwater world with colorful coral reefs.",
    "A vast desert with sand dunes and a distant oasis.",
    "An intricate maze with twists and turns.",
    "A majestic castle on a hilltop with a moat.",
    "A spooky graveyard at night with eerie mist.",
    "A beautiful garden with blooming flowers.",
    "A surreal city with impossible architecture.",
    "A space station orbiting a planet.",
    "A serene lake surrounded by mountains.",
    "A quaint village with cobblestone streets and thatched roofs.",
    "A starry night sky with a shooting star.",
    "A futuristic high-speed train station.",
    "A majestic waterfall with a rainbow.",
    "A peaceful forest with a hidden waterfall.",
    "A bustling city with skyscrapers and traffic.",
    "A creepy abandoned prison with barred windows.",
    "A hidden cave with glowing crystals.",
    "A beautiful sunset over a rolling countryside.",
    "A futuristic sports arena with holographic displays.",
    "A beautiful autumn forest with colorful leaves.",
    "A snowy forest with a lone cabin.",
    "A beautiful seaside town with a harbor.",
    "A mysterious underground bunker.",
    "A beautiful park with a fountain and benches.",
    "A futuristic laboratory with advanced technology.",
    "A beautiful countryside with green fields and blue skies.",
    "A futuristic city with flying cars.",
    "A beautiful river with a waterfall.",
    "A creepy abandoned hospital with broken windows.",
    "A beautiful beach with palm trees and turquoise water.",
    "A futuristic shopping mall with escalators and neon lights.",
    "A beautiful snowy forest with a frozen lake.",
    "A quaint small town with colorful houses.",
    "A futuristic office with glass walls and minimal design.",
    "A beautiful garden with a gazebo.",
    "A futuristic spaceship exploring the galaxy.",
    "A beautiful spring meadow with blooming flowers.",
    "A creepy abandoned factory with rusted machinery.",
    "A beautiful snowy mountain with a ski resort.",
    "A futuristic city with flying drones and robots."
]